start porting adjoint notebooks to autograd
flexcompute/tidy3d-notebooks pull request #111
Opened 2024-05-16 19:05 UTC by tylerflex

2024-05-30 14:05 UTC, tylerflex commented
@daquintero could you verify whether I set this up properly :D  no need to go through notebook material itself, thanks.

2024-05-31 09:26 UTC, daquinteroflex commented on Invdes.ipynb
Hello! I think you need to rename this file

2024-05-31 09:27 UTC, daquinteroflex commented on docs/features/autograd.rst
Will Autograd 7 exist our of curiosity?

2024-05-31 09:28 UTC, daquinteroflex requested changes
Congrats on such big changes and new features! Just a few tiny details I raised

2024-05-31 12:12 UTC, tylerflex commented on docs/features/autograd.rst
Yea, I just haven't implemented field monitor support yet. but coming soon!

2024-05-31 12:15 UTC, tylerflex commented on Invdes.ipynb
oh, thanks. Seems in pre/2.7 it's still the wrong file name? when you fixed it for the 2.7.0rc2 release did that change not propagate to pre/2.7? There were a few other things missing right? maybe I should add `jaxComplexPolySlab`?

2024-05-31 12:17 UTC, tylerflex commented on Invdes.ipynb
actually I'm totally confused.. this is configured in `tidy3d/`. And I think it was already added.

2024-05-31 12:17 UTC, merged

2024-05-31 12:37 UTC, daquinteroflex commented on Invdes.ipynb
Ooh I think in order not to have to go through the whole release flow with updating the notebook submodule, I manually updated it on the tidy3d-docs files when we did the release, but it seems I missed fixing it on the source accidentally sorry. Whereas the jaxcomplexpolyslab was a PR onto the tidy3d source which was synced onto tidy3d_docs so the source is updated