Patch antenna simulation with DirectivityMonitor
flexcompute/tidy3d-notebooks pull request #209
Opened 2024-12-17 23:21 UTC by QimingFlex

2024-12-18 22:16 UTC, dmarek-flex commented
Great to get a nice simple example of a patch antenna. Thanks @QimingFlex! I suggest structuring this notebook as a tutorial of the `DirectivityMonitor`, which allows users to calculate most antenna parameters of interest. Maybe we could call it "AntennaParameters.pynb".

A couple of things I noticed off the bat:

1. You should include an update to the documentation to link to this notebook. You can add it to `docs/features/microwave.rst`.
2. Link to the `DirectivityMonitor` API and other classes you mention in the markdown cells of your notebook.  (wherever your monitor ends up here https://docs.flexcompute.com/projects/tidy3d/en/latest/api/monitors.html). You can find examples of this is our other notebooks.
3. You reference a paper with [1], but I don't see the actual citation.

I'll do another pass soon.

2024-12-19 16:11 UTC, tomflexcompute requested changes
Thanks @QimingFlex for the great example on the most iconic antenna. It would be very helpful for people to get started in antenna modeling. A few comments:

- Could you add the notebook title to 'tidy3d-notebooks/docs/case_studies/microwave.rst'?

- We can add this image as the thumbnail. 
<img width="400" alt="patch_antenna" src="https://github.com/user-attachments/assets/25ec89a2-8956-4d6b-aa80-db6819112b49" />

- Could you add metadata according to [this](https://www.notion.so/flexcompute/How-to-add-metadata-to-a-case-study-or-tutorial-notebook-696f9dd642f14964af4eb1242226451e)? Also feel free to reference the metadata of other notebooks in the repo if the instructions are not clear. 

- In the plotting, I think Damian created a way to change the unit to mm? That might make it look better to avoid all the large numbers in the ticks. 

- In the introduction it references [1] but there is no bibliography of the citation.

- `_internal_construct_smatrix` is used to calculate the s parameters. This seems to be an internal method that's not designed for users? Why not use the regular `run()` of the modeler?


- Since patch antenna is probably one of the most fundamental RF devices, this example could be the first example a lot of RF users will read. I think it might be helpful to add more comments and instructions before each code block to explain things in a bit more detail. This way even brand new tidy3d users can learn the basic concepts and workflow more easily. For example, what does the `DirectivityMonitor` do, what's a `TerminalComponentModeler`, etc. And link them to the API reference for readers who want to check out the API. Typically when making examples we imagine the reader knows close to nothing about tidy3d and the examples can guide them through the entire workflow step by step. 

- Two typos I noticed:
"paramters" -> "parameters"
"materail" -> "material"

2024-12-19 22:34 UTC, QimingFlex commented
> Great to get a nice simple example of a patch antenna. Thanks @QimingFlex! I suggest structuring this notebook as a tutorial of the `DirectivityMonitor`, which allows users to calculate most antenna parameters of interest. Maybe we could call it "AntennaParameters.pynb".
> 
> A couple of things I noticed off the bat:
> 
>     1. You should include an update to the documentation to link to this notebook. You can add it to `docs/features/microwave.rst`.
> 
>     2. Link to the `DirectivityMonitor` API and other classes you mention in the markdown cells of your notebook.  (wherever your monitor ends up here https://docs.flexcompute.com/projects/tidy3d/en/latest/api/monitors.html). You can find examples of this is our other notebooks.
> 
>     3. You reference a paper with [1], but I don't see the actual citation.
> 
> 
> I'll do another pass soon.

Thanks @dmarek-flex ! Corrected and ready for another review.

2024-12-19 22:36 UTC, QimingFlex commented
> Thanks @QimingFlex for the great example on the most iconic antenna. It would be very helpful for people to get started in antenna modeling. A few comments:
> 
>     * Could you add the notebook title to 'tidy3d-notebooks/docs/case_studies/microwave.rst'?
> 
>     * We can add this image as the thumbnail.
> 
> 
> <img alt="patch_antenna" width="400" src="https://private-user-images.githubusercontent.com/116006359/397447644-25ec89a2-8956-4d6b-aa80-db6819112b49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2NDc5NTksIm5iZiI6MTczNDY0NzY1OSwicGF0aCI6Ii8xMTYwMDYzNTkvMzk3NDQ3NjQ0LTI1ZWM4OWEyLTg5NTYtNGQ2Yi1hYTgwLWRiNjgxOTExMmI0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOVQyMjM0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2FlYTBjOGNmM2ZhODg0ZjQ1MTg0ZmI4NjAxYzA5MzFkM2Y0NDY3ZTdmZDA5NTAwOTdkZTM5MmI2M2E2MWRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.05e14ZrLrXZPY6HRJRcbTIYjXoEnbQTE94Q2FDjZgl4">
> 
>     * Could you add metadata according to [this](https://www.notion.so/flexcompute/How-to-add-metadata-to-a-case-study-or-tutorial-notebook-696f9dd642f14964af4eb1242226451e)? Also feel free to reference the metadata of other notebooks in the repo if the instructions are not clear.
> 
>     * In the plotting, I think Damian created a way to change the unit to mm? That might make it look better to avoid all the large numbers in the ticks.
> 
>     * In the introduction it references [1] but there is no bibliography of the citation.
> 
>     * `_internal_construct_smatrix` is used to calculate the s parameters. This seems to be an internal method that's not designed for users? Why not use the regular `run()` of the modeler?
> 
>     * Since patch antenna is probably one of the most fundamental RF devices, this example could be the first example a lot of RF users will read. I think it might be helpful to add more comments and instructions before each code block to explain things in a bit more detail. This way even brand new tidy3d users can learn the basic concepts and workflow more easily. For example, what does the `DirectivityMonitor` do, what's a `TerminalComponentModeler`, etc. And link them to the API reference for readers who want to check out the API. Typically when making examples we imagine the reader knows close to nothing about tidy3d and the examples can guide them through the entire workflow step by step.
> 
>     * Two typos I noticed:
>       "paramters" -> "parameters"
>       "materail" -> "material"

Thanks @tomflexcompute ! All corrected and the `run_sim` and `_internal_construct_smatrix` will be replaced by web run once my PR on polarized field get merged.

2024-12-20 15:44 UTC, dmarek-flex commented
> * Could you add the notebook title to 'tidy3d-notebooks/docs/case_studies/microwave.rst'?

@tomflexcompute I suggested to @QimingFlex to add it as a feature tutorial explaining the `DirectivityMonitor`. Does that make sense to you?

2024-12-20 15:49 UTC, tomflexcompute commented
> > * Could you add the notebook title to 'tidy3d-notebooks/docs/case_studies/microwave.rst'?
> 
> @tomflexcompute I suggested to @QimingFlex to add it as a feature tutorial explaining the `DirectivityMonitor`. Does that make sense to you?

Yeah that could be good. This example can be a good standalone example as well so I'll leave it up to you guys to decide. If we make it a feature tutorial, we need to add more descriptions to introduce how all these antenna quantities are calculated by the monitor. Otherwise we can make a separate feature tutorial to introduce it.

2024-12-20 16:11 UTC, QimingFlex commented
@dmarek-flex @tomflexcompute adding it as a feature tutorial sounds good as it mostly interact with DirectivityMonitor.

2024-12-23 21:54 UTC, dmarek-flex requested changes
Ran out of time before finish review, so I'll do another pass.

- Should use heading level two ("##") for each section, other than the first title.
- Looking at the reference, there seems to be an observable difference in the S parameters. I am guessing it is an issue with the source placement in the middle of the input trace, and I don't think the exact source position in your simulation matches the reference. Can you try to get a better match with the reference? I would suggest shortening the length of the strip so that the lumped port and strip start are at the same location, i.e., `feed_y=16*mm`
- A little confusing in your plots of the structure and mesh, the plot of the port is actually at `-18mm`, but the `plot_grid` call changes it to -`20mm`

2024-12-23 21:54 UTC, dmarek-flex commented on AntennaCharacteristics.ipynb
> +    "In this notebook, we will demonstrate how to use Tidy3D to simulate a rectangular patch antenna [1] and compute key performance metrics. These include S-parameters using the [TerminalComponentMo
I think we should link to the latest version in the docs, so

[https://docs.flexcompute.com/projects/tidy3d/en/latest/api/_autosummary/tidy3d.plugins.smatrix.TerminalComponentModeler.html](https://docs.flexcompute.com/projects/tidy3d/en/latest/api/_autosummary/tidy3d.plugins.smatrix.TerminalComponentModeler.html)

2024-12-23 21:54 UTC, dmarek-flex commented on AntennaCharacteristics.ipynb
> +    "<img src=\"img/PatchAntenna.png\" alt=\"MIM\"  width=\"400\"/>\n",
`alt` should describe the image, so why not "Schematic of the patch antenna".

2024-12-23 21:54 UTC, dmarek-flex commented on AntennaCharacteristics.ipynb
> +    "plt.ylabel('|S11| (dB)')\n",
Put `11` as subscript

2025-01-03 01:55 UTC, QimingFlex commented
>     * Looking at the reference, there seems to be an observable difference in the S parameters. I am guessing it is an issue with the source placement in the middle of the input trace, and I don't think the exact source position in your simulation matches the reference. Can you try to get a better match with the reference? I would suggest shortening the length of the strip so that the lumped port and strip start are at the same location, i.e., `feed_y=16*mm`



The S-parameters look much better if moving the port as close as to the boundaries.

2025-01-03 21:02 UTC, dmarek-flex commented
> The S-parameters look much better if moving the port as close as to the boundaries.

Nice, agreed! Is there a reason why you placed the port just next to the end of the microstrip feed? You should be able to put it right at the end.

2025-01-03 23:19 UTC, weiliangjin2021 approved these changes
Very nice and clean notebook!

2025-01-03 23:19 UTC, weiliangjin2021 commented on AntennaCharacteristics.ipynb
> +    "    subpixel=True, # Use subpixel smoothing for accuracy\n",
shutoff and subpixel are using the default values. So no need to define them explicitly here.

2025-01-06 21:53 UTC, dmarek-flex approved these changes
Looks great @QimingFlex! Please just remember to change code using local interface with web interface, and change  `_internal_construct_smatrix` .

Also it looks nice to go through and emphasize python inline code and such in the markdown cells using \`. For example, where you introduce the `LumpedPort` and `TerminalComponentModeler`. 

Also maybe one typo mistake in the definition of Poynting vector. I think it should be EthetaHphi* -  EphiHtheta* with a minus sign.

2025-01-07 15:12 UTC, merged